### ISSUE TITLE
todo en esta semana

### ISSUE THREAD

**Issue by ceci-lo** [ceci-lo/pizzeria#1]
- [ ] Arreglar espacios de cards
- [ ] sacar sombras oscuras
- [ ] hacer el json como map en js

**Comment by ceci-lo** [comment]
- [x] Agregar boton para ver contraseña en pagina login.html 
- [x] centrar en el medio el contenido de la pagina
- [x] Agregar Link de foggot your password sobre input password
- [x] agregar titulo de la pagina
